// apps/web/pages/login.tsx
import { app } from '../lib/firebase'
import { getAuth, signInWithPopup, EmailAuthProvider, signInWithEmailAndPassword } from 'firebase/auth'
import { useState } from 'react';
import { getFunctions, httpsCallable } from 'firebase/functions'
import Router, { useRouter } from 'next/router';
import Header from '../components/header';
import { Trans } from '@lingui/macro';

const auth = getAuth(app);
const functions = getFunctions(app);

export default function Login(props) {
    const user = null;
    const username = null;

    return (
        <main>
            <Header small />
                <SignInForm />
        </main>
    )
}

function SignInForm() {
    const router = useRouter();
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    function signIn(e) {
        e.preventDefault();
        signInWithEmailAndPassword(auth, email, password).then((userCredential) => {
            router.push('/');
            console.log(userCredential.user);
        }).catch((error) => {
            console.log(`[${error.code}]: ${error.message}`);
        });
    }

    return (
        <div className='w-screen absolute top-1/2 left-0 -translate-y-1/2'>
            <h1 className='text-center text-2xl font-semibold mb-2'><Trans id="logIn">Login</Trans></h1>
            <form onSubmit={signIn} className='flex flex-col px-3'>
                <label className='flex flex-col font-semibold'>
                    <span className='ml-1'><Trans id="email">Email</Trans></span>
                    <input type="email" value={email} onChange={e => setEmail(e.target.value)} className='border-2 border-black rounded-lg text-xl px-1 py-1' />
                </label>
                <label className='flex flex-col font-semibold mt-2'>
                    <span className='ml-1'><Trans id="password">Password</Trans></span>
                    <input type="password" value={password} onChange={e => setPassword(e.target.value)} className='border-2 border-black rounded-lg text-xl px-1 py-1' />
                </label>
                <button type='submit' className='border-2 border-black mt-3 rounded-lg py-1 text-lg font-semibold border-violet-800'><Trans id="logIn">Login</Trans></button>
            </form>
        </div>
    );
}

// apps/internal/src/routes/login.svelte
<script context="module" lang="ts">
	export const prerender = true;
</script>

<script lang="ts">
import { browser } from '$app/env';

import { goto } from '$app/navigation';

	import {auth} from '$lib/firebase';
	import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';

	let email = '';
	let password = '';
	let error = '';

    if (browser) {
        if(auth.currentUser) {
            goto('/');
        }
    }

	async function login(e) {
		e.preventDefault();
		try {
			const res = await signInWithEmailAndPassword(auth, email, password);
		} catch (err) {
            console.log(err.code)
            switch (err.code) {
                case 'auth/invalid-email':
                    error = 'Invalid email';
                    break;
                case 'auth/user-disabled':
                    error = 'User disabled';
                    break;
                case 'auth/user-not-found':
                    error = 'User not found';
                    break;
                case 'auth/wrong-password':
                    error = 'Wrong password';
                    break;
                default:
                    error = 'Unknown error';
                    console.log(error)
            }
		}
	}
</script>

<svelte:head>
	<title>Login</title>
</svelte:head>

<section>
	<div class="px-2 max-w-sm mx-auto mt-5">
		<h1 class="text font-semibold text-center text-2xl">Login</h1>
		<form on:submit={login}>
			<label class="label">
				<span class="label-text">Email</span>
				<input class="input" type="email" bind:value={email} />
			</label>
			<label class="label">
				<span class="label-text">Password</span>
				<input class="input" type="password" bind:value={password} />
			</label>
			<p class="text-red-400">{error}</p>
			<button class="button float-right mt-3">Login</button>
		</form>
	</div>
</section>
